test:
    age: 22
    name: testUser

#随机值
com:
    heardfate:
        random:
            # 随机字符串
            secret: ${random.value}
            # 随机int
            number: ${random.int}
            # 随机long
            bignumber: ${random.long}
            # UUID值
            uuid: ${random.uuid}
            # 10以内的随机数
            lessThan: ${random.int(10)}
            # 10-100的随机数
            inRange: ${random.int[10,100]}
            # 100-1000的随机数,100前面和1000后面可以是 -，(，[ 等任意字符 int.inRange: ${random.int-100,1000-}
            inRange2: ${random.int(100,1000)}
spring:
    profiles:
        active: dev